//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Pages.Health.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddPrescription_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddPrescription_aspx() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Pages.Health.App_LocalResources.AddPrescription.aspx", typeof(AddPrescription_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string btnSend_Text {
            get {
                return ResourceManager.GetString("btnSend.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administration.
        /// </summary>
        internal static string lclAdmin_Text {
            get {
                return ResourceManager.GetString("lclAdmin.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frequency.
        /// </summary>
        internal static string lclFrequency_Text {
            get {
                return ResourceManager.GetString("lclFrequency.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medicine.
        /// </summary>
        internal static string lclMedicine_Text {
            get {
                return ResourceManager.GetString("lclMedicine.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agarimo - Prescription Creation.
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page.Title", resourceCulture);
            }
        }
    }
}
