//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicine()
        {
            this.Prescription = new HashSet<Prescription>();
        }
    
        public long medicineId { get; set; }
        public long registerNumber { get; set; }
        public string medName { get; set; }
        public string labName { get; set; }
        public System.DateTime authDate { get; set; }
        public string medStatus { get; set; }
        public System.DateTime statusDate { get; set; }
        public string ATCCode { get; set; }
        public string activePrinc { get; set; }
        public short activePrincN { get; set; }
        public string commercialized { get; set; }
        public string yellowTriangle { get; set; }
        public string observations { get; set; }
        public string substitutes { get; set; }
        public string affectsConduction { get; set; }
        public string supplyIssues { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prescription> Prescription { get; set; }
    }
}
