//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prescription()
        {
            this.Dose = new HashSet<Dose>();
        }
    
        public long prescriptionId { get; set; }
        public long patient { get; set; }
        public System.DateTime creationDate { get; set; }
        public long medicine { get; set; }
        public short frequency { get; set; }
        public string administration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dose> Dose { get; set; }
        public virtual Medicine Medicine1 { get; set; }
        public virtual Patient Patient1 { get; set; }
    }
}
