//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAction
    {
        public long actionId { get; set; }
        public System.DateTime actionTime { get; set; }
        public long actor { get; set; }
        public int performedAction { get; set; }
        public string stringVal { get; set; }
        public Nullable<long> intVal { get; set; }
        public string actionText { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
